apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Create the argocd-manager service account
  - argocd-manager-serviceaccount.yaml

  # Create the argocd-manager role with token
  - argocd-manager-clusterrole.yaml
  - argocd-manager-secrets.yaml

  # Create the argocd-manager role binding
  - argocd-manager-clusterrolebinding.yaml
